name: React App Build and Deploy

on: [push, workflow_dispatch]

# Environment variables
env:
  RESOURCE-GROUP: reactwebapp_rg
  LOCATION: uksouth
  TEMPLATE-FILE: infra/webapp.bicep
  SUBSCRIPTION-ID: 96047339-523f-41da-a50a-c1f7e9a635ec
  WEBAPP-NAME: interview-reactapp-webapp

jobs:
  # Build, test and publish the React web project in repository
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Prepare runner for the desired Node.js version
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      # Install Node.js dependencies
      - name: Install dependencies
        run: cd my-app && npm install

      # Build the React app
      - name: Build React app
        run: cd my-app && npm run build

      # Test the React app
      - name: Test with React
        run: cd my-app && npm test

      # Zip the build folder
      - name: Zip build folder
        run: |
          cd my-app/build
          zip -r ../../app.zip .

      # Upload the published website code artifacts
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: app.zip

      # Upload the Bicep template as artifacts for next job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE-FILE }}

  # Use Bicep to deploy infrastructure + publish webapp
  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: "Development"
    steps:
      # Download the publish files created in the previous job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: react-app
          path: react-app

      # Download the Bicep templates from the previous job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: bicep-template
          path: bicep-template

      # Login to your Azure subscription using a service principal (credentials stored as GitHub Secret in repo)
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Azure WebApp using Bicep file
      - name: Deploy Azure WebApp using Bicep file
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION-ID }}
          resourceGroupName: ${{ env.RESOURCE-GROUP }}
          template: bicep-template/webapp.bicep
          parameters: "webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}"
          failOnStdErr: false

      # Publish the website to Azure App Service using CLI
      - name: Publish Website to WebApp using CLI
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy --name ${{ env.WEBAPP-NAME }} --resource-group ${{ env.RESOURCE-GROUP }} --src-path react-app/app.zip --type zip
